### ISSUE TITLE
Unexpected result when pcaMethod=FALSE (default)

### ISSUE THREAD

**Issue by brainprint** [matloff/polyreg#1]
After reading your paper from Arxiv, I am learning how to use your package. Today I have faced this unexpected result, based on your example for `polyFit`. Am I doing something wrong?

```
library(polyreg)

y <- mtcars[, 1]
data <- cbind(mtcars[, -1], y) # make y column the last column
f <- polyFit(data, 2, 2, "lm", TRUE, 0.9)
pred <- predict(f, data[, -ncol(data)])
plot(y, pred, col = "blue", pch = 19, asp = c(1, 1))

f1 <- polyFit(data, 2, 2, "lm")
pred1 <- predict(f1, data[, -ncol(data)])
points(y, pred1, col = "red", pch = 19, asp = c(1, 1))
```

![polyreg](https://user-images.githubusercontent.com/17748369/41798429-8f115a6c-7665-11e8-8436-6b53e56e1524.png)

**Comment by matloff** [comment]
Why is it unexpected?

**Comment by brainprint** [comment]
I was not expecting 100% accuracy when using the default option (`f1` and `pred1`).

```
all.equal(pred1, y)
[1] "names for target but not for current"
```

Then I have tried a random dataset to check the accuracy.

```
library(polyreg)

kRow <- 1e2
kCol <- 1e2
kNum <- kRow * kCol

data <- matrix(data = rnorm(kNum), kRow, kCol)
y <- data[, ncol(data)]

f <- polyFit(data, 2, 2, "lm", TRUE, 0.9)
pred <- predict(f, data[, -ncol(data)])
plot(y, pred, col = "blue", pch = 19, asp = c(1, 1))

f1 <- polyFit(data, 2, 2, "lm")
pred1 <- predict(f1, data[, -ncol(data)])
points(y, pred1, col = "red", pch = 19, asp = c(1, 1))

> all.equal(pred1, y)
[1] "names for target but not for current"
> all.equal(pred, y)
[1] "names for target but not for current"
> all.equal(pred, pred1)
[1] TRUE
```

Now, for both cases, 100% accuracy for a random dataset. Am I missing something?

**Comment by matloff** [comment]
Sounds like a classic case of overfitting, in this case perfect, due to having a number of parameters greater than or equal to the sample size. I'll check it out.

**Comment by brainprint** [comment]
Thank you for the clarification. I believe I understood my mistake. I have tried changing the number of columns x rows to better comprehend the relationship between parameters and sample size.

**Comment by matloff** [comment]
Thanks for getting back to us.
