### ISSUE TITLE
Interrupted by browser() in line #58 of function polyFit()

### ISSUE THREAD

**Issue by jclchan** [matloff/polyreg#10]
I'm using browser to access server version of RStudio.  When I run the function 'polyFit()', it would pop up a bug window, triggered by browser() in line #58 of that function.  Can you help to resolve this issue?  Thanks a lot!

**Comment by rdrr1990** [comment]
just did, thanks for flagging that!

**Comment by matloff** [comment]
Thanks, Pete.

Norm

**Comment by jclchan** [comment]
Thanks for your quick fix!
