### ISSUE TITLE
get_interactions fails when an interaction uses all variables

### ISSUE THREAD

**Issue by kramsretlow** [matloff/polyreg#18]
Hi and thanks for your work on polyreg.  I think I've found a small bug.

It relates to the case where we want to generate the "saturated" polynomial, with all possible terms.  The problem arises with the unique term that has all of the variables multiplied together.  

The easiest way to reproduce the problem is to run `polyreg:::get_interactions(c("A","B","C"),3)`, which returns 

```
Error in apply(combos, 2, paste, collapse = " * ") : 
  dim(X) must have a positive length
```

Inside `get_interactions()`, there is the line 

```r
interactions[[i]] <- apply(combos, 2, paste, collapse = " * ")
```  

But if there is only one combination of the type, by this  time `combos` is a vector, with `dim(combos)` equal to `NULL`, hence `apply` crashes.

It is probably an easy fix but you might have your own preferred way of handling it.

Users would probably only want to get all possible terms in cases with very few variables, which may seem trivial, but I am but I am using it for a real problem where I've been asked to get a "simple to calculate" approximation to some simulator output.

**Comment by rdrr1990** [comment]
Thanks! I look into this but it seems to missing a `drop=FALSE`.

**Comment by rdrr1990** [comment]
Just pushed a fix, thanks again!
